//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Retailer
    {
        public int RetailerId { get; set; }
        public string RetailerName { get; set; }
        public Nullable<int> DistributorId { get; set; }
        public string State { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public Nullable<int> Phone { get; set; }
        public Nullable<int> MobileNo { get; set; }
    
        public virtual Distributor Distributor { get; set; }
    }
}
