//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int StockID { get; set; }
        public int ProductID { get; set; }
        public int DistributorID { get; set; }
        public int StockQuantity { get; set; }
    
        public virtual Distributor Distributor { get; set; }
        public virtual Product Product { get; set; }
    }
}
